cursor:
  style:
    blinking: Always
  blink_interval: 500
font:
  normal:
    family: Roboto Mono for Powerline
    # family: JetBrainsMono Nerd Font
  size: 12
key_bindings:
- { key: Space, mods: Control, chars: "\x00" }
